[build]
  publish = "."  # Serve files from the root directory
  functions = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://*.stripe.com, https://*.kit.fontawesome.com, https://*.maxcdn.bootstrapcdn.com; style-src 'self' https://*.fonts.googleapis.com, https://*.kit.fontawesome.com, https://*.maxcdn.bootstrapcdn.com; img-src 'self' https://*.imgur.com, https://*.i.ibb.co, https://*.raw.githubusercontent.com; connect-src 'self' https://*.getform.io; font-src 'self' https://*.fonts.gstatic.com, https://*.maxcdn.bootstrapcdn.com; frame-ancestors 'none'; base-uri 'self';"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"
